### ISSUE TITLE
Clickable links in <a> tags being unnecessarily converted

### ISSUE THREAD

**Issue by pwindle** [PaeP3nguin/LinkBot#1]
Affected Page:
https://www.youtube.com/watch?v=GRD-xvlhGMc

In the description of this youtube video LinkBot converts most of the links although they are already clickable. 
Most of the links have a `...` at the end which is left untouched with the original correct link.

One strange exception is the fourth link in the description:
`https://www.youtube.com/subscription_...`
`https://www.youtube.com` is incorrectly converted to a link
`/subscription_...` is correctly left as the original link.

**Comment by PaeP3nguin** [comment]
Thanks for the bug report! Since modern web pages tend not to load all at once, Linkbot also linkifies any changes to the webpage, including when the Youtube description loads in. Linkbot normally doesn't link things that are already links, but it turns out that I forgot to include the check in that crucial place! I'll get an update pushed out soon.

**Comment by PaeP3nguin** [comment]
I've uploaded a new version to the Chrome store. It should go live in an hour or so and you'll probably get the update within 24 hours. If you want the update faster, you can go to your extensions settings, check the Developer mode box, then click the"Update extensions now" button.

Thanks again for the bug report!

**Comment by pwindle** [comment]
Yep, it's working well for me now. Thanks!
