### ISSUE TITLE
Add getting started and contributing instructions

### ISSUE THREAD

**Issue by fucusy** [PaeP3nguin/LinkBot#4]
I would like to improve LinkBot, but I don't know how can we compile it to chrome extension by self?

**Comment by fucusy** [comment]
we may add some steps for new developer

**Comment by fucusy** [comment]
but, I already know how to make it by trying

**Comment by PaeP3nguin** [comment]
Good point, when I uploaded this onto Github, I only meant for people to be able to look at the code and make sure there's nothing suspicious going on, since the extension I used to use to do this turned into adware :(

But if people actually want to contribute to the project, I'll need to add some developer instructions!
